require_relative 'authentication/access'
require_relative 'authentication/auth_strategy'
require_relative 'authentication/middleware'
require_relative 'authentication/static_token_auth'
require_relative 'authentication/fetch_token_auth'
